### ISSUE TITLE
EFCore.Sharding.oracle使用问题

### ISSUE THREAD

**Issue by zhaijh** [Coldairarrow/Colder.Admin.AntdVue#100]
项目为当前最新项目
1、本地Unti项目安装本地EFCore.Sharding.oracle最新稳定版 如下图
![image](https://user-images.githubusercontent.com/5182649/94257559-0e4a9900-ff5e-11ea-9c9f-04d40476d3c2.png)
2、安装最低版本
![image](https://user-images.githubusercontent.com/5182649/94257794-6f726c80-ff5e-11ea-9383-3985d6d50854.png)
3、按提示Microsoft.EntityFrameworkCore.Relational 升级到最新稳定版3.1.6
 如果升级到3.1.7 或3.1.8 会有以下冲突
![image](https://user-images.githubusercontent.com/5182649/94258692-cf1d4780-ff5f-11ea-8906-7769c499dc54.png)
4、EFCore.Sharding.oracle 不能装最新稳定版,可以安装低版本
5、运行项目，提示如下错误
![image](https://user-images.githubusercontent.com/5182649/94259191-a6498200-ff60-11ea-9dba-83b7582a8482.png)

![123](https://user-images.githubusercontent.com/5182649/94259834-abf39780-ff61-11ea-8fc3-2454ae3b7428.png)

6、大佬看看我是少安装包了还是版本问题了

**Comment by Coldairarrow** [comment]
EF Core3.1对Oracle支持是不久前的，如果你原来用的EFCore.Sharding.2.x  
那么需要整体升级：先将EFCore.Sharding.2.x完全卸载，再安装最新版EFCore.Sharding.Oracle试下

**Comment by fly4312** [comment]
问题解决了么，我的是EFCore.Sharding.MySql 。提示需要安装EFCore.Sharding.MySql ，但的确安装了好几遍。从3.1.1 到3.1.8.1 都有问题。后面是提示找不到“:“Could not load type 'MySql.Data.MySqlClient.MySqlClientFactory' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92” 翻来覆去就这俩问题。sqlserver 没问题

**Comment by Coldairarrow** [comment]
MySqlConnector不能用1.0.0.0版本的，要降到0.6x版本

**Comment by zhaijh** [comment]
EFCore.Sharding安装最新，再安oracle

**Comment by zhaijh** [comment]
@fly4312 你用最新的代码，直接装最新的EFCore.Sharding.MySql就行，反复弄几次，我反复几次就可以了
