### ISSUE TITLE
问下新版的没有Task任务了？

### ISSUE THREAD

**Issue by Xiaobaiaixiaobai** [Coldairarrow/Colder.Admin.AntdVue#101]
问下新版的没有Task任务了？

**Comment by Coldairarrow** [comment]
啥意思？

**Comment by Xiaobaiaixiaobai** [comment]
原先版本可以配置定时执行任务，  新的版本没有了吗？

**Comment by Coldairarrow** [comment]
有啊

**Comment by Xiaobaiaixiaobai** [comment]
![Uploading QQ图片20201012093059.png…]()
是这个类吗？

**Comment by Coldairarrow** [comment]
看不见

**Comment by Xiaobaiaixiaobai** [comment]
Coldairarrow.Util类库底下的  ClassLibrary ---》  TaskQeury.cs    类吗？

**Comment by Coldairarrow** [comment]
JobHelper

**Comment by Xiaobaiaixiaobai** [comment]
找到了 谢谢，  问下这个类的使用有没有例子

**Comment by fly4312** [comment]
----- 原始邮件 -----
发件人：Xiaobaiaixiaobai <notifications@github.com>
收件人："Coldairarrow/Colder.Admin.AntdVue" <Colder.Admin.AntdVue@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re:_[Coldairarrow/Colder.Admin.AntdVue]_问下新版的没有Task任务了？_(#101)
日期：2020年10月12日 09点23分



原先版本可以配置定时执行任务，  新的版本没有了吗？

**Comment by Xiaobaiaixiaobai** [comment]
![image](https://user-images.githubusercontent.com/35687605/95802723-d3ec4480-0d30-11eb-87e6-03337432e273.png)
我是在Startup里面这样调用，可以执行。我想问下这个是不是最优的调用写法？

**Comment by Xiaobaiaixiaobai** [comment]
我是在Startup里面这样调用，可以执行。我想问下这个是不是最优的调用写法？

![QQ图片20201013085038](https://user-images.githubusercontent.com/35687605/95802881-37767200-0d31-11eb-9130-30710f1c9935.png)

**Comment by xiaopohou** [comment]
稍等一下，我爱人这边要调整一下你们的配色！！！！她加你们微信！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Coldairarrow/Colder.Admin.AntdVue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 上午8:51
收件人:&nbsp;"Coldairarrow/Colder.Admin.AntdVue"<Colder.Admin.AntdVue@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Coldairarrow/Colder.Admin.AntdVue] 问下新版的没有Task任务了？ (#101)





 
我是在Startup里面这样调用，可以执行。我想问下这个是不是最优的调用写法？

**Comment by ysq5202121** [comment]
hangfire
