### ISSUE TITLE
两个数据库1个是colder的，一个是业务的。

### ISSUE THREAD

**Issue by fly4312** [Coldairarrow/Colder.Admin.AntdVue#103]
一个数据库是colder 的数据库，一个数据库是业务的，就是用base_dblink中包含的数据库。生成后，这个数据怎么提取？文档说的是在stutup配置，但这个连接字符串是在数据库中的。这怎么解？

**Comment by Coldairarrow** [comment]
注入IDbFactory
调用IDbFactory.GetDbAccessor
