### ISSUE TITLE
目前已知BUG列表

### ISSUE THREAD

**Issue by ysq5202121** [Coldairarrow/Colder.Admin.AntdVue#107]
1.修改密码无法重复两次修改,由于缓存原因没有刷新原始密码.
2.权限保存后会删除原先的ID，导致角色授权中的权限id不生效，必须重新设置一次.

**Comment by Coldairarrow** [comment]
权限保存后会删除原先的ID，导致角色授权中的权限id不生效，必须重新设置一次.

**Comment by Coldairarrow** [comment]
两次修改密码问题已修复

**Comment by ysq5202121** [comment]
@Coldairarrow  实际应用非常不方便，假如有10个角色设置好了某一个菜单下面的所有权限,那么我在重新新增一个权限，则所有角色对于该菜单权限全部失效，需要全部重新设置一次，如果角色多，那不敢想象。。。。，扩展一次权限就需要重新设置一次所有的。我觉得实际应用是不合理的，客户用了必须骂娘.
所有关于这一块逻辑有必要调整，需要检查历史权限，而不是先删后加，一刀切。
