### ISSUE TITLE
Bad IL format 打包之后发布在iis上报错“Bad IL format ”

### ISSUE THREAD

**Issue by zhaijh** [Coldairarrow/Colder.Admin.AntdVue#108]
使用的是当前最新开源项目   数据库用的是mysql 本地运行没有问题，发布后在本地运行exe和服务器上都出现以下错误
1、错误日志
[Uploading log20201109.txt…]()
2、图片
![image](https://user-images.githubusercontent.com/5182649/98520201-b0bfa100-22ac-11eb-9fd1-9a76147f9015.png)

网上找到解决方案 没有解决这个问题
![image](https://user-images.githubusercontent.com/5182649/98520107-938ad280-22ac-11eb-8ee2-0cc8f505d3b3.png)

**Comment by Coldairarrow** [comment]
.NET Core别用IIS
