### ISSUE TITLE
执行sql语句调方法  GetListBySqlAsync 报错 

### ISSUE THREAD

**Issue by zhaijh** [Coldairarrow/Colder.Admin.AntdVue#113]
执行SQL 
![image](https://user-images.githubusercontent.com/5182649/100306317-18305d00-2fde-11eb-926f-4260ce2da8ec.png)

莫名奇妙的string 
![image](https://user-images.githubusercontent.com/5182649/100306266-f6cf7100-2fdd-11eb-9592-d0e06cc670fa.png)
 SQL输出 运行没问题
![image](https://user-images.githubusercontent.com/5182649/100306427-4e6ddc80-2fde-11eb-94c8-02d7ce075235.png)
表设计
![image](https://user-images.githubusercontent.com/5182649/100306181-c1c31e80-2fdd-11eb-8a78-3eff7649333c.png)

**Comment by Coldairarrow** [comment]
最新版5.0试下
