### ISSUE TITLE
数据库使用 Heroku 的 PostgreSQL 时碰到问题 

### ISSUE THREAD

**Issue by SpongeKevin** [Coldairarrow/Colder.Admin.AntdVue#14]
[HeroKu](https://www.heroku.com/) 是一个云端託管平台，有提供免费的方案的 PostgreSQL 使用
我想要使用这个平台来做为线上测试的平台并且暂时使用他的 PostgreSQL 

以下是我的问题描述与我所做的更动，想请教是否有没注意的程式逻辑，亦感谢大佬开源出如此好用的框架造福大家

我连接本地计算机上 PostgreSQL 运作正常，但当我使用了 HeroKu PostgreSQL 时出现了错误
我依照了网路上的 [教学](https://blog.cashwu.com/blog/asp-net-core-mvc-heroku-postgresql/) 修改了

Colder.Admin.AntdVue\src\Coldairarrow.DataRepository\DbFactory.cs 行 61
```
case DatabaseType.PostgreSql: builder.UseNpgsql(dbConnection, optionBuilder =>
{
    optionBuilder.RemoteCertificateValidationCallback((sender, certificate, 
    chain, errors) => true);
}); break;
```

Colder.Admin.AntdVue\src\Coldairarrow.Api\appsettings.json
```
"BaseDb": " {---连接字串---};sslmode=Require;"
```
但依然於 Coldairarrow.DataRepository -> BaseDbContext ->SaveChanges() 行29 出現以下問題
```
System.Security.Authentication.AuthenticationException: 'The remote certificate is invalid according to the validation procedure.
```
如有不够充足的问题描述请不吝告知，定补上也希望大佬帮帮萌新解惑

**Comment by Coldairarrow** [comment]
抱歉这个问题我也不清楚

**Comment by Coldairarrow** [comment]
建议使用原生EF Core试下

**Comment by SpongeKevin** [comment]
目前开了其他专案测试 EF Core 连接 Heroku 的 PostgreSQL 数据库用同连接字串是成功的   
我再找找为什么在 Colder.Admin.AntdVue 会有异常，目前猜测是 EF Core 版本问题，我更新测试看看
感谢你的建议

**Comment by Coldairarrow** [comment]
有结果了啊

**Comment by SpongeKevin** [comment]
尚未解决
目前公司项目要赶，预计明天才开始处理这问题

**Comment by Coldairarrow** [comment]
OK，有结果了反馈下

**Comment by SpongeKevin** [comment]
同步下处理进度

目前初步排除了 EF CORE 版本的问题
我在个人测试专案使用了最新的 3.1.2 版本与 Colder.Admin.AntdVue 使用的 2.2.4 版本皆可访问 HEROKU 的数据库

现在猜测的问题点为我在 Colder.Admin.AntdVue\src\Coldairarrow.DataRepository\DbFactory.cs 行 61
设置的
```
case DatabaseType.PostgreSql: builder.UseNpgsql(dbConnection, optionBuilder =>
{
    optionBuilder.RemoteCertificateValidationCallback((sender, certificate, 
    chain, errors) => true);
}); break;
```
中的 RemoteCertificateValidationCallback 并没有很好的动作，导致依然会去因为验证问题而出现错误

状况尚未解决，我需要研究一下这机制如何运作
