### ISSUE TITLE
多线程下如何处理IDbAccessor 

### ISSUE THREAD

**Issue by zxz524** [Coldairarrow/Colder.Admin.AntdVue#156]
https://github.com/Coldairarrow/Colder.Admin.AntdVue/blob/c8b6bd5a3bd9c6ae0e84caa72c63a05e9fab29d9/src/Coldairarrow.Business/BaseBusiness.T.cs#L47

        /// <summary>
        /// 业务仓储接口(支持软删除),支持联表操作
        /// 注：若需要访问逻辑删除的数据,请使用IDbAccessor.FullRepository
        /// 注：仅支持单线程操作
        /// </summary>
        public IDbAccessor Db { get; }

**Comment by Coldairarrow** [comment]
using var scope=scopeFactory.CreateScope()
var db=scope.ServiceProvider.GetService<IDbAccessor>()
思路就是自行在后台线程创建scope，然后再获取IDbAccessor
