### ISSUE TITLE
完善代码

### ISSUE THREAD

**Issue by MyJimmyZhou** [Coldairarrow/Colder.Admin.AntdVue#17]
非常好的开发模板！
这里是不是忘记添加代码实现了：   
     public async Task<int> UpdateAnyAsync<T>(List<T> entities, List<string> properties) where T : class, new()
        {
            return await UpdateAnyAsync(entities, properties);
        }
另外，可否尝试添加AsNoTracking。

**Comment by Coldairarrow** [comment]
v3.0完成
