### ISSUE TITLE
 await q.Where(where).ToListAsync() 报错

### ISSUE THREAD

**Issue by 908705107** [Coldairarrow/Colder.Admin.AntdVue#23]
q是IQueryable<Article_Info>类型

- return await q.Where(where).GetPagination(pagination).ToListAsync();--能正常返回数据
- return await q.Where(where).ToListAsync(); --报错

报错信息
The source IQueryable doesn't implement IAsyncEnumerable<Coldairarrow.Entity.ArticleManage.Article_Info>. Only sources that implement IAsyncEnumerable can be used for Entity Framework asynchronous operations.

**Comment by Coldairarrow** [comment]
无法复现，请进群沟通

**Comment by Coldairarrow** [comment]
v3.0完成
