### ISSUE TITLE
有2個建議，希望能支持一下

### ISSUE THREAD

**Issue by Baiqu** [Coldairarrow/Colder.Admin.AntdVue#24]
1. appsettings.Development.json 能支持這個配置文件，這樣方式調試時，使用不同的數據庫地址
我目前在使用Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"); 判斷環境來達到此目的，不知道方法可好。不過再更新代碼時，這些都會被替換，不太方便。

2.GlobalSwitch.cs 文件中public static readonly DatabaseType DatabaseType = DatabaseType.MySql;
这个数据库类型，是否考虑放在appsettings.json文件中呢？更新代碼時，這些都被替換了。

**Comment by Coldairarrow** [comment]
这个建议非常好
正在着手后续版本更新

**Comment by Coldairarrow** [comment]
繁体字？台湾的？

**Comment by Baiqu** [comment]
謝謝，繁體字也不僅僅是台灣在用。

**Comment by Coldairarrow** [comment]
v3.0完成

**Comment by Baiqu** [comment]
辛苦了，謝謝。
