### ISSUE TITLE
试用了一下很好很强大,但是有个小小的建议

### ISSUE THREAD

**Issue by DUWENINK** [Coldairarrow/Colder.Admin.AntdVue#3]
目前大部分netcorer的项目应该都是(也有可能是我见识短浅)Code First的吧,自动升成代码的确不错,但是要是可以基于codefirst进行生成就好了,比如根据codefirst ef自动生成数据库,然后通过框架生成代码并且不覆盖手写的ef实体

**Comment by Coldairarrow** [comment]
恰恰相反，数据库的控制权肯定掌握在开发人员手中（大公司甚至有DBA专门管理），要以实际出发

**Comment by DUWENINK** [comment]
建议之二:发现作者大大使用了NetCore3.0 但是3.0推荐的EF却用了 `Microsoft.EntityFrameworkCore, Version=2.2.4.0(在Coldairarrow.Util中)`但是很多方法作者大大似乎是用了微软的,我在升级ef3.0的过程中发现  类`QueryModelGenerator`和 `RelationalQueryModelVisitor`在3.0中已经不见了作者大大是否可以修复下升级3.0的问题

**Comment by Coldairarrow** [comment]
EFCore暂不升级，因为有些数据库还不支持EFCore3.0

**Comment by DUWENINK** [comment]
作者大大那automap是否计划升级
