### ISSUE TITLE
this.$http.post(）如何手动定义请求的content-type

### ISSUE THREAD

**Issue by 908705107** [Coldairarrow/Colder.Admin.AntdVue#32]
我折腾了好久， 发现框架里post请求的this.$http.post(）是在axios-plugin.js进行封装的（里面自动携带token、rootUrl、axios拦截回调等功能），也就是说发送post请求得用this.$http.post(）。
但是经过我多次测试，发现
1、如果post里传的参数是序列化后的对象（即Json.stringif），那么F12查看header头里的Content-type会变成application/x-www-form-urlencoded
2、如果post里传的参数是json对象（不序列化），Content-type 自动变为application/json
----------------------------------------------------------------------------------------------
Content-type的不同对后台接口有较大影响。我的接口参数定义的是实体类的话就必须满足下面两种情况的任意一种：
1、contentType为application/json，则必须要传递序列化过的对象；
2、application/x-www-form-urlencoded，则前端直接传递json类型的对象即可。 

**但是这两种都和现有的测试结果正好相反，也就是说无法满足 application/json--序列化 或application/x-www-form-urlencoded--  Json对象。**
-------------------------------------------------------------------------------------------------
解决思路：1、可否在不全局修改content-type情况下 指定某个 this.$http.post(）是何种content-type，我在网上看到  .ajax{}和.axios是可以指定content-type的，但是这个this.$http.post(）网上说在后面加 emulateJSON: true，经过测试没有任何作用，还是自动变换content-type，并且emulateJSON: true是vue-resource里的属性，我全局搜索项目没发现vue-resource的代码
2、可否满足像我上面说的两种情况一样，根据传的参数的对象不同，自动变化Content-Type(本框架确实实现了，但是和我想要的结果正好相反，我不清楚它是如何自动根据参数来变换Content-Type的)

附上我参考的博客：https://www.cnblogs.com/landeanfen/p/5337072.html#_label4

**Comment by Coldairarrow** [comment]
axios-plugin.js只是对axios进行了最简单的封装而已
你可以看下框架的所有API接口请全是application/json
不知道你到底要什么效果

**Comment by 908705107** [comment]
把参数stringif()序列化后 就不是application/json了

**Comment by 908705107** [comment]
我想要的是 序列化后上传的参数 也是application/json  而不是application/x-www-form-urlencoded

**Comment by Coldairarrow** [comment]
这不是我框架的问题，你可以研究下axios

**Comment by 908705107** [comment]
> 这不是我框架的问题，你可以研究下axios

解决了 后面加上  { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }就行了
