### ISSUE TITLE
后端JsonParamter拦截器报错导致进不了接口的断点，注释JsonParamter拦截器可进断点

### ISSUE THREAD

**Issue by 908705107** [Coldairarrow/Colder.Admin.AntdVue#33]
前端：
var bannerpic = [1, 2, 3]
var params = {
            bannerpic: bannerpic
}
this.$http.post('/ArticleManage/Article_Info/AddData', params).then(resJson => {
            if (resJson.Success) {
              this.$message.success('操作成功!')
              this.visible = false
            } else {
              this.$message.error(resJson.Msg)
            }
---------------------------------
F12查看  
Content-Type: application/json
RequsetPayload参数：
bannerpic: [1, 2, 3]
------------------------------------
报错：在JsonParamter拦截器阶段报错
在Extention.Object.cs下的ChangeType_ByConvert（）方法第245行
▶ | $exception | {"Invalid cast from 'System.String' to 'System.Collections.Generic.List`1[[Coldairarrow.Util.PicDTO, Coldairarrow.Util, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'."} | System.InvalidCastException

**Comment by Coldairarrow** [comment]
v3.0修复
