### ISSUE TITLE
建议表模型多设计几种

### ISSUE THREAD

**Issue by cfzy** [Coldairarrow/Colder.Admin.AntdVue#34]
在另个开源项目里面发现的设计方式：
1、TopBasePoco是框架所有模型的基类，它只定义了一个Guid的主键，所有其他模型都必须直接或间接继承TopBasePoco，否则框架的其他自动化操作无法执行。
2、BasePoco是框架所有内置模型的基类，它在TopBasePoco的基础上增加了创建人，修改人，创建时间和修改时间四个字段，对于大多数模型，这些字段都是需要的，建议用户自定义的模型都继承BasePoco。
3、PersistPoco在BasePoco的基础上增加了IsValid字段，指示框架对这类模型进行假删除。

这个项目里面给了3种表模型，希望本项目也能更灵活点。

**Comment by Coldairarrow** [comment]
这些都属于约束
软删除框架也支持，实际使用上没差别

**Comment by cfzy** [comment]
是的，但真正项目的确有的表完全不需要创建人、创建时间这些，就是固定的基础数据，不由操作人员编辑。

**Comment by Coldairarrow** [comment]
没有也没关系啊，并不是强制有的
