### ISSUE TITLE
添加mysql报错

### ISSUE THREAD

**Issue by jxhsjxhs** [Coldairarrow/Colder.Admin.AntdVue#47]
![image](https://user-images.githubusercontent.com/16410777/81586944-e7455d80-93e8-11ea-90e1-d417bfa67182.png)
![image](https://user-images.githubusercontent.com/16410777/81586953-ead8e480-93e8-11ea-9f64-b43e42204c11.png)

**Comment by Coldairarrow** [comment]
数据库类型为MySql，注意大小写
