### ISSUE TITLE
file encoding

### ISSUE THREAD

**Issue by EdenWoo** [Coldairarrow/Colder.Admin.AntdVue#6]
Can you fix page encoding for some pages under 04Business/Business_Manage.

**Comment by Coldairarrow** [comment]
thanks,I wiil fix it in the future

**Comment by Icechen2015** [comment]
Core 3 代码生成 新增 不了

**Comment by Icechen2015** [comment]
`CREATE TABLE [dbo].[Enterprise_Info](
	[Id] [varchar](50) NOT NULL,
	[CreateTime] [datetime] NOT NULL,
	[CreatorId] [varchar](50) NULL,
	[CreatorRealName] [nvarchar](50) NULL,
	[Deleted] [bit] NOT NULL,
	[LegalPerson] [nvarchar](50) NULL,
	[Capital] [nvarchar](50) NULL,
	[UnifiedSocialCode] [nvarchar](50) NULL,
	[DateOfEstablishment] [nvarchar](50) NULL,
	[PollutionSourceAddress] [nvarchar](50) NULL,
	[AdministrativeDivision] [nvarchar](50) NOT NULL,
	[IndustrialPark] [nvarchar](50) NULL,
	[ProductionAddress] [nvarchar](100) NULL,
	[AddressOfUnitBranch] [nvarchar](100) NULL,
	[IndustryCategory] [int] NOT NULL,
	[TechnicalDirector] [nvarchar](50) NULL,
	[CommissioningTime] [datetime] NOT NULL,
	[EAOrgan] [nvarchar](100) NULL,
	[ApprovalTime] [datetime] NOT NULL,
	[EiaSolidWasteManage] [nvarchar](50) NULL,
	[ContingencyPlan] [nvarchar](50) NULL,
	[AcceptanceDocument] [nvarchar](50) NULL,
	[DischargePermit] [nvarchar](50) NULL,
	[CleanerProduction] [nvarchar](50) NULL,
	[NuclearAndRadiation] [nvarchar](50) NULL,
	[CSolidWasteManage] [nvarchar](50) NULL,
	[TypesOfMainAirPollutants] [nvarchar](50) NULL,
	[EmissionLawOfAirPollutants] [nvarchar](50) NULL,
	[ExecutiveStandardForAirPollutantDischarge] [nvarchar](100) NULL,
	[TypesOfMainPollutantsInWastewater] [nvarchar](100) NULL,
	[DischargeLawOfWasteWaterPollutants] [nvarchar](100) NULL,
	[Down] [nvarchar](255) NULL,
 CONSTRAINT [PK_Enterprise_Info_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'主键' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'Id'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建时间' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'CreateTime'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建人Id' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'CreatorId'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建人姓名' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'CreatorRealName'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'否已删除' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'Deleted'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'法人' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'LegalPerson'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'资本' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'Capital'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'统一社会代码' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'UnifiedSocialCode'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'成立日期' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'DateOfEstablishment'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'污染源地址' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'PollutionSourceAddress'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'所属行政区划' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'AdministrativeDivision'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'所属工业园区' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'IndustrialPark'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'生产地址' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'ProductionAddress'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'单位分厂地址' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'AddressOfUnitBranch'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'行业类别' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'IndustryCategory'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'技术负责人' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'TechnicalDirector'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'投产时间' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'CommissioningTime'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'审批机构' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'EAOrgan'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'审批时间' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'ApprovalTime'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'环评固废管理' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'EiaSolidWasteManage'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'应急预案' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'ContingencyPlan'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'验收文件' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'AcceptanceDocument'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'排污许可证' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'DischargePermit'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'清洁生产' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'CleanerProduction'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'核与辐射' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'NuclearAndRadiation'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'污染固废管理' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'CSolidWasteManage'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'大气主要污染物种类' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'TypesOfMainAirPollutants'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'大气污染物排放规律' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'EmissionLawOfAirPollutants'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'大气污染物排放执行标准' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'ExecutiveStandardForAirPollutantDischarge'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'废水主要污染物种类' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'TypesOfMainPollutantsInWastewater'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'废水污染物排放规律' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'DischargeLawOfWasteWaterPollutants'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'下载' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Enterprise_Info', @level2type=N'COLUMN',@level2name=N'Down'
GO

ALTER TABLE [dbo].[Enterprise_Info] ADD  CONSTRAINT [DF_Enterprise_Info_Deleted]  DEFAULT ('false') FOR [Deleted]
GO`

**Comment by Icechen2015** [comment]
这是我的表，你拿来试试

**Comment by Coldairarrow** [comment]
异常截图呢

**Comment by Coldairarrow** [comment]
最新版已解决编码问题
