### ISSUE TITLE
取消系统日志输出到数据库

### ISSUE THREAD

**Issue by Coldairarrow** [Coldairarrow/Colder.Admin.AntdVue#67]
高并发下会占用有限的数据库资源，应该输出到ElasticSearch

**Comment by xiaopohou** [comment]
收到！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Coldairarrow"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 下午3:26
收件人:&nbsp;"Coldairarrow/Colder.Admin.AntdVue"<Colder.Admin.AntdVue@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Coldairarrow/Colder.Admin.AntdVue] 取消日志输出到数据库 (#67)





 
取消日志输出到数据库，高并发下会占用有限的数据库资源，应该输出到ElasticSearch
