### ISSUE TITLE
发布部署后，登录成功后会跳转404页面

### ISSUE THREAD

**Issue by zhengguibin-ZGB** [Coldairarrow/Colder.Admin.AntdVue#69]
本地运行正常。但发布后，登录成功后无法正常进入页面，直接进入404页面，更改了登录成功后进入的路由后也无效，都是跳转404页面

**Comment by Coldairarrow** [comment]
这是vue路由问题，主流解决方法使用Nginx，详情参考下文
https://www.jianshu.com/p/989d8bc719c4
