### ISSUE TITLE
实体映射

### ISSUE THREAD

**Issue by qq760270775** [Coldairarrow/Colder.Admin.AntdVue#7]
当表存在多个主键的时候 实体多个字段加上特性key，映射失败

**Comment by Coldairarrow** [comment]
支持的，需要加特性
```
/// <summary>
        /// 主键
        /// </summary>
        [Key, Column(Order = 1)]
        public String Id { get; set; }
```

**Comment by qq760270775** [comment]
你这个市单个主键，我说的是多个主键啊，假设这样

        /// <summary>
        /// 主键
        /// </summary>
        [Key, Column(Order = 1)]
        public string Id { get; set; }
		
		        /// <summary>
        /// 角色ID
        /// </summary>
        [Column("role_id")]
		[Key, Column(Order = 1)]
        public string RoleId { get; set; }

**Comment by Coldairarrow** [comment]
RoleId 的Order要改为2或其它，按照顺序来

**Comment by qq760270775** [comment]
试过了多，只要加了多个key特性，查询的时候就报错
实体类型“xxx”具有使用数据注释定义的复合主键。 要设置复合主键,请使用fluent

**Comment by Coldairarrow** [comment]
抱歉，EF Core不支持这种写法，原来的EF6是支持的
EFCore需要下面这种写法
https://www.learnentityframeworkcore.com/configuration/fluent-api/haskey-method
