### ISSUE TITLE
Keyword not supported

### ISSUE THREAD

**Issue by yf2468** [Coldairarrow/Colder.Admin.AntdVue#70]
输入用户密码按登录后，VS2019报错。

**Comment by yf2468** [comment]
Extention.IServiceCollection.cs第53行return _generator.CreateInterfaceProxyWithTarget(aInterface, serviceProvider.GetService(aType), castleInterceptor);错误

System.ArgumentException:“Keyword not supported: 'charset'.”

**Comment by Coldairarrow** [comment]
连接字符串问题，详情参考https://www.connectionstrings.com/
