### ISSUE TITLE
部门表创建后部门名称乱码

### ISSUE THREAD

**Issue by cmmi** [Coldairarrow/Colder.Admin.AntdVue#78]
SqlServer下varchar 类型存储中文需要加上  COLLATE Chinese_PRC_CS_AS_WS 否则需要改成 nvarchar类型。

-- ----------------------------
-- Table structure for Base_Department
-- ----------------------------
CREATE TABLE [Base_Department] (
[Id] varchar(50) NOT NULL ,
[CreateTime] datetime NOT NULL ,
[CreatorId] varchar(50) NULL ,
[Deleted] bit NOT NULL DEFAULT ('false') ,
[Name] varchar(50) COLLATE Chinese_PRC_CS_AS_WS NULL ,
[ParentId] varchar(50) NULL 
)

-- ----------------------------
-- Table structure for Base_Department
-- ----------------------------
CREATE TABLE [Base_Department] (
[Id] varchar(50) NOT NULL ,
[CreateTime] datetime NOT NULL ,
[CreatorId] varchar(50) NULL ,
[Deleted] bit NOT NULL DEFAULT ('false') ,
[Name] nvarchar(50)  NULL ,
[ParentId] varchar(50) NULL 
)

**Comment by Coldairarrow** [comment]
已修复
