### ISSUE TITLE
webapi不支持连接sqlserver2008R2，请问有什么解决办法

### ISSUE THREAD

**Issue by 908705107** [Coldairarrow/Colder.Admin.AntdVue#82]
OFFSET' 附近有语法错误。\r\n在 FETCH 语句中选项 NEXT 的用法无效。

好像是因为efcore分页默认是sql2012版本以上  和2008r2不同 引起的，需要在哪里配置能正常连上2008r2

**Comment by Coldairarrow** [comment]
升级到2012不就好了
