### ISSUE TITLE
布尔值

### ISSUE THREAD

**Issue by EdenWoo** [Coldairarrow/Colder.Admin.AntdVue#9]
数据库里的布尔值类型为tinyint(4)的时候，API出现
  "Msg": "Operator '=' incompatible with operand types 'SByte' and 'Boolean'"，
是不是生成的时候Map有错误？

**Comment by Coldairarrow** [comment]
mysql支持不是很完善，需要手动调整字段类型

**Comment by Coldairarrow** [comment]
已修复,将tinyint对应bool
