### ISSUE TITLE
是否能够根据自己的命名生成工程文件

### ISSUE THREAD

**Issue by ysq5202121** [Coldairarrow/Colder.Admin.AntdVue#90]
目前下载过来解决方案名字都是Coldairarrow，一般实际应用都需要改名字的，手动改很麻烦，是否有一个页面直接输入项目名称，然后点击下载就可以呢？

**Comment by ysq5202121** [comment]
输入项目名称--》下载生成-->对应的项目名称工程

**Comment by Coldairarrow** [comment]
意义不大
