### ISSUE TITLE
请教大神:单元测试中如何使用接口注入

### ISSUE THREAD

**Issue by xiaohanlaila** [Coldairarrow/Colder.Admin.AntdVue#92]
如题，请问下大神，在单元测试中，如何直接的使用接口进行功能测试，个人配置了一些东西和方法，但是无法通过构造函数注入，还请大神可以帮忙解惑

**Comment by Coldairarrow** [comment]
参考 https://github.com/Coldairarrow/EFCore.Sharding/blob/master/src/EFCore.Sharding.Tests/Startup.cs

**Comment by xiaohanlaila** [comment]
非常感谢
