### ISSUE TITLE
缓存更新疑虑

### ISSUE THREAD

**Issue by xiaohanlaila** [Coldairarrow/Colder.Admin.AntdVue#96]
为啥缓存更新中的逻辑里调用的是Remove的方法，是我个人理解问题还是大神手误

![image](https://user-images.githubusercontent.com/38322997/92447418-c4d21e00-f1e9-11ea-8241-f106b3a04bb7.png)

**Comment by xiaohanlaila** [comment]
1

**Comment by ysq5202121** [comment]
删除了缓存后，会重新创建一个，类似于更新，我记得缓存是没有update，都是移除
